name: github-pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Api tests
      run: |
        python manage.py shell
        pip install pipenv --upgrade
        pipenv install --system
        pytest -s -v --durations=0
    - name: Lint with flake
      run: |
        pip install flake8
        flake8



